name: application-ci

on:
  push:

jobs:
  build-app:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Build Application
        run: ./gradlew assembleDebug

      - name: Publish Build Artifact(APK)
        uses: actions/upload-artifact@v2.2.0
        with:
          name: DeeeepLinkk APK
          path: |
            **/*.apk

